POST http://localhost:4000/student/assessment/updateScore HTTP/1.1
content-type: application/json

{
"courseName":"DBMS",
"studentId":"12006018",
"assessmentScore":"100"
}
###
GET http://localhost:4000/student/assessment/DMS HTTP/1.1
content-type: application/json


